#Given a non-empty array of integers nums, every element appears twice except for one. Find that single one
class Solution(object):
    def singleNumber(self, nums):
        result=0
        for i in nums:
            result^=i

        return result

        """for i in nums:
            if nums.count(i)==1:
                return i
        
        """

        """
        :type nums: List[int]
        :rtype: int
        """

#You are given two strings s and t.

#String t is generated by random shuffling string s and then add one more letter at a random position.

#Return the letter that was added to t

class Solution(object):
    def findTheDifference(self, s, t):
        res=0

        for ch in s:
            res^=ord(ch)

        for ch in t:
            res^=ord(ch)

        return chr(res)
        
    """    l=list(t)
        
        for i in s:
            
            l.remove(i)
       
        for i in l:
            return l[0]

            """

        
